# Generated by Django 3.2.8 on 2021-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectre', '0002_alter_weatherpoint_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherpoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='weatherpoint',
            name='time',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
